"""add caller_phone column

Revision ID: 1b1c57ac7274
Revises: d79737970451
Create Date: 2026-03-07 06:28:24.638967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c57ac7274'
down_revision = 'd79737970451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caller_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.drop_column('caller_phone')

    # ### end Alembic commands ###
