"""initial schema

Revision ID: 59cf268240bd
Revises: 
Create Date: 2026-02-22 07:55:11.976086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cf268240bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ingest_email_token', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=True),
    sa.Column('monthly_voicemail_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_voicemail_used', sa.Integer(), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_end', sa.DateTime(), nullable=True),
    sa.Column('overage_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingest_email_token')
    )
    op.create_table('digest_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('total_voicemails', sa.Integer(), nullable=True),
    sa.Column('urgent_count', sa.Integer(), nullable=True),
    sa.Column('non_urgent_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('voicemails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('transcription_provider', sa.String(length=50), nullable=True),
    sa.Column('transcribed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('triage_category', sa.String(length=100), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voicemail_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('crisis_flag', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('digest_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['voicemail_id'], ['voicemails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voicemail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_cards')
    op.drop_table('voicemails')
    op.drop_table('user')
    op.drop_table('digest_logs')
    op.drop_table('clinic')
    # ### end Alembic commands ###
