"""add retry system

Revision ID: 8ca9ae870d34
Revises: a8c9ede9f210
Create Date: 2026-03-09 19:05:43.564914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca9ae870d34'
down_revision = 'a8c9ede9f210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.drop_column('last_error')

    # ### end Alembic commands ###
