"""add action routing fields

Revision ID: d05b019c088a
Revises: 1b1c57ac7274
Create Date: 2026-03-09 06:54:52.181482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05b019c088a'
down_revision = '1b1c57ac7274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recommended_action', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('recommended_action')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
