"""add s3_key for idempotent ingestion

Revision ID: d79737970451
Revises: 59cf268240bd
Create Date: 2026-03-06 12:40:29.678888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79737970451'
down_revision = '59cf268240bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_key', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_voicemails_s3_key', ['s3_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('s3_key')

    # ### end Alembic commands ###
