"""add triage cards

Revision ID: ea495b37917a
Revises: 
Create Date: 2026-02-13 12:09:59.451943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea495b37917a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voicemail_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('crisis_flag', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['voicemail_id'], ['voicemails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voicemail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_cards')
    # ### end Alembic commands ###
